export const projects = [
  {
    id: 1,
    name: 'Todo App',
    text: 'Todo List créée entièrement en PHP, SQL. Vous pouvez modifier, rayer, supprimer les tâches à faire.',
    gitlink: 'https://github.com/Kazimor-5/todo-app',
    link: '',
    img: './images/todo-app.png',
  },
  {
    id: 2,
    name: 'Dice Game',
    text: 'Lancé de dé aléatoire créé en PHP qui vous affichera les résultats obtenus par rapport au nombre de dés jetés.',
    gitlink: 'https://github.com/Kazimor-5/Dice-Game',
    link: '',
    img: './images/dice-game.png',
  },
  {
    id: 3,
    name: 'Shi Fu Mi',
    text: "Jeu de Shi Fu Mi créé en PHP qui vous fera jouer face à l'ordinateur. Faites votre choix et soumettez le contre l'ordinateur. Pour obtenir les logs de connexion, regardez dans la console de développement de votre navigateur.",
    gitlink: 'https://github.com/Kazimor-5/Shi-Fu-Mi',
    link: '',
    img: './images/ShiFuMi.png',
  },
  {
    id: 4,
    name: 'Blog',
    text: 'Blog personnel créé sous Symfony. Vous pouvez vous créer un compte, vous connecter et ajouter des articles.',
    gitlink: 'https://github.com/Kazimor-5/blog',
    link: '',
    img: './images/blog.png',
  },
  {
    id: 5,
    name: 'Liste des personnages dans Rick et Morty',
    text: "Liste des personnages dans la série animée Rick et Morty faites sous react.js. Elle est basée sur l'API Rick et Morty.",
    gitlink: 'https://github.com/Kazimor-5/rick-and-morty-api',
    link: 'https://rick-and-morty-api-project.netlify.app',
    img: './images/rick-and-morty.png',
  },
  {
    id: 6,
    name: 'Todo App en react',
    text: 'Todo App réalisée sous react.js. Vous pouvez ajouter, editer et supprimer les tâches à faire.',
    gitlink: 'https://github.com/Kazimor-5/todoapp-react-project',
    link: 'https://todoapp-react-project-abf.netlify.app',
    img: './images/todo-app-react.png',
  },
  {
    id: 7,
    name: "Panier d'achat en react",
    text: "Panier d'achat réalisée sous react.js. Vous pouvez ajouter, retirer des articles ou alors les supprimer.",
    gitlink: 'https://github.com/Kazimor-5/cart-project-redux',
    link: 'https://cart-project-react-redux.netlify.app',
    img: './images/cart-project.png',
  },
  {
    id: 8,
    name: 'API de jobs',
    text: 'API de jobs réalisée en Node.js avec express. La base de données est crée via Mongodb.',
    gitlink: '',
    link: 'https://jobs-api-project1.herokuapp.com/api/docs/',
    img: './images/job-api.png',
  },
  {
    id: 10,
    name: 'Pokedex avec scroll infini',
    text: 'Pokedex réalisé sous react.js. Le traitement des données a été fait grâce à axios. Elle répertorie tout les pokémons existant à ce jours et intègre un sytème de scroll infini.',
    gitlink: 'https://github.com/Kazimor-5/pokedex-project',
    link: 'https://pokedex-api-infinite-scrolling.netlify.app',
    img: './images/pokedex.png',
  },
];
